# PyTorch Tensor Basics

This notebook provides a basic introduction to PyTorch tensors, covering creation, attributes, operations, and the NumPy bridge.

In [1]:
import torch
import numpy as np

## 1. Creating Tensors

### From data

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print("From data:\n", x_data)

From data:
 tensor([[1, 2],
        [3, 4]])


### From a NumPy array

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("\nFrom NumPy array:\n", x_np)


From NumPy array:
 tensor([[1, 2],
        [3, 4]])


### From another tensor (inherits properties, unless overridden)

In [4]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print("\nOnes like x_data:\n", x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print("\nRandom like x_data (float):\n", x_rand)


Ones like x_data:
 tensor([[1, 1],
        [1, 1]])

Random like x_data (float):
 tensor([[0.1538, 0.9524],
        [0.8027, 0.2875]])


### With random or constant values

In [ ]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"\nRandom Tensor:\n {rand_tensor}")
print(f"Ones Tensor:\n {ones_tensor}")
print(f"Zeros Tensor:\n {zeros_tensor}")

## 2. Tensor Attributes

In [5]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 3. Tensor Operations

### Move tensor to GPU if available

In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Tensor is now on device: {tensor.device}")
else:
    print("CUDA not available, tensor remains on CPU.")

### Indexing and slicing

In [ ]:
tensor_slice = tensor[0, :]
print("\nFirst row of tensor:", tensor_slice)

tensor_element = tensor[0, 0].item()
print("First element of tensor:", tensor_element)

### Joining tensors

In [ ]:
tensor1 = torch.ones(4, 4)
tensor2 = torch.zeros(4, 4)
t1_t2_stack = torch.stack([tensor1, tensor2, tensor1], dim=0)
print("\nStacking tensors (dim=0):\n", t1_t2_stack)
print("Shape after stacking:", t1_t2_stack.shape)

### Concatenating tensors

In [ ]:
cat_h = torch.cat([tensor1, tensor2], dim=1) # Horizontal concatenation
cat_v = torch.cat([tensor1, tensor2], dim=0) # Vertical concatenation
print("\nConcatenating horizontally (dim=1):\n", cat_h)
print("Concatenating vertically (dim=0):\n", cat_v)

### Arithmetic operations

In [ ]:
tensor_ops = torch.ones(2, 2)
print("\nOriginal tensor for operations:\n", tensor_ops)

#### Element-wise multiplication

In [ ]:
print("\nElement-wise product:\n", tensor_ops.mul(tensor_ops))
print("Element-wise product (shorthand *):\n", tensor_ops * tensor_ops)

#### Matrix multiplication

In [ ]:
matrix_mul_result = tensor_ops.matmul(tensor_ops.T)
print("\nMatrix multiplication:\n", matrix_mul_result)
print("Matrix multiplication (shorthand @):\n", tensor_ops @ tensor_ops.T)

#### In-place operations (denoted with an _ suffix)

In [ ]:
print("\nOriginal tensor_ops:\n", tensor_ops)
tensor_ops.add_(5)
print("In-place add (tensor_ops.add_(5)):\n", tensor_ops)

### Reshaping

In [ ]:
reshaped_tensor = tensor.view(2, 6) # Flatten example
print("\nOriginal tensor shape:", tensor.shape)
print("Reshaped tensor (2x6):\n", reshaped_tensor)
print("Reshaped tensor shape:", reshaped_tensor.shape)

## 4. NumPy Bridge

### Tensor to NumPy array

In [ ]:
numpy_from_tensor = tensor.cpu().numpy() # .cpu() is necessary if tensor is on GPU
print("Tensor to NumPy:\n", numpy_from_tensor)
print("Type of numpy_from_tensor:", type(numpy_from_tensor))

### Changes in the tensor reflect in the NumPy array (and vice-versa)

In [ ]:
tensor.add_(1)
print("\nTensor after in-place add:\n", tensor)
print("NumPy array after tensor change (same memory):\n", numpy_from_tensor)

### NumPy array to Tensor

In [ ]:
np_array_new = np.ones(5)
torch_from_np = torch.from_numpy(np_array_new)
print("\nNumPy to Tensor:\n", torch_from_np)

### Changes in the NumPy array reflect in the tensor (and vice-versa)

In [ ]:
np.add(np_array_new, 1, out=np_array_new)
print("NumPy array after in-place add:\n", np_array_new)
print("Tensor after NumPy change (same memory):\n", torch_from_np)